### ISSUE TITLE
How to adjust fishing range?

### ISSUE THREAD

**Issue by Forkinator** [tiemonl/Bit-Heroes-Fishing-Bot#12]
Hey, I just want to say great job on this. This is fantastic. Just have a question;

Using the Trolling rod, the bot casts at 40 range (out of 44) every time when I select the trolling rod (which is what I am using in-game) which gives me 44 range max. Is there something I missed? Is there a way to configure this?

Thank you

Edit: Found the debug options and calibrated the range. Seems to be perfect at 1394 range for me. Don't know if using a high-resolution desktop makes a difference.  I also have a nice g-sync monitor but I get the feeling it doesn't matter. It's probably more about the resolution. I followed the directions and set the in-game resolution to 800 x 600 and then pressed the find start location button. 

You can delete this, although maybe we can try to find out why it doesn't find the right value(1394) right away. I know its probably different for each person.

**Comment by tiemonl** [comment]
Hey, 

So when the program starts out there are already set values in the code for each rod of an approximate time which works for most people. Those values stop working when server lag is introduced and that’s why I have debug controls. I can’t know everyone’s value to begin with. If I calibrated the program everytime it started, like Get Times does in the debug controls, that would make a terrible UI and I would get a lot more issues being posted saying the program doesn’t fish at the beginning.

The healthy alternative was to keep the average values for each fishing rod and if that didn’t work for users they could go out of their way to change it and let the program fish for however many bait they have with their value. 

There are two different ways for that. Users can increase or decrease the value manually, or press get times to let the program see what the average is and change it to that value. With lag for some people it might be more than 1394 or less than 1394 which was the case for you.

The resolution of the monitor doesn’t matter and gsync doesn’t matter. If the game is set to 800x600 it will take up the same amount of pixels on any monitor resolution, and that is what the program is designed for, to read input from the 800x600 game screen.

I hope that answers your issue. Feel free to give me feedback on the bot if you think it could be improved or a new feature can be added. Thanks for the star as well! Much appreciated!

**Comment by Forkinator** [comment]
Thanks for the response. That makes perfect sense and it's nice to learn more about this stuff. I agree with the way you ordered things. I had no idea that it was due to lag. I have such a fast internet connection along with a beefy PC, and Bit Heroes is such a small game compared to most of the games i play that I thought there was no way any sort of lag could be the culprit. Shows what little i know. 

I really like the app so far. I would have to go out of my way to really think about any kind of changes that would improve the fishing bot.

If anything, maybe add a way to select which bait to use/not use. Thats all I can really think of and you have probably thought of that already.


Thanks so much for putting in the time to make this app. It really helps me catch more fish.  I am temporarily on a medication that makes my response time noticeably worse, so this is a great tool to help me  to catch fish without wasting tons of bait.

Can I ask one thing about how this app works? 

I don't know much about programming/coding, so I am going out on a limb here guessing that this app works by scanning for the colors of the fishing bar when trying to catch a fish and when the bar hits the first pixel (or whatever set pixel you want ) then it inputs the "Catch" button (aka spacebar). 

Is it possible to make the catching of fish accurate? I  feel like I can tell that its physically trying to hit the green 100% mark by looking for and stopping right at the first green pixel that it detects, but maybe there is a sweet-spot somewhere and that can be adjusted somehow? Again, this is me speaking  out of almost no experience, so I apologize if this sounds moronic or infeasible. 


Again, thank you so much for making this app and for taking the time to read this.

**Comment by Forkinator** [comment]
I think I might have found something that could be improved. 

So every now and then, you know how after you cast, there is an exclamation mark above the bobber,  and then right after that, the screen pops up with the moving fish and the green "mark" that you need to line up?(we will call this the "catching" stage)  Well, I noticed that some fish, move extremely fast at the beginning of the catching stage and the bot has trouble catching them. 

The bot has trouble catching these fish because it tries to hit the green mark as soon as the catching stage shows up and becasue some fish move extremely fast at the start of this stage, and then normalise to going their normal speed. 

I believe the solution  to this is to code in a 1 second delay of when the bot  starts looking for the green "mark".  This gives the "fish" enough time to start moving how it should, and that will make it easier for the bot to catch the fish since some fish move so eratically at the very beginning.

Again, this only happens at the very beginning of the catching stage. Sometimes the fish moves extremely fast past the green "mark" and that's the only time I see the bot have trouble, as it moves very quickly. 

Let me know what you think.

**Comment by tiemonl** [comment]
Hey, so the way the program works it checks the the color of the casting bar. It is continuously checking the bar until it changes color the "max blue." Once it reaches that first max blue, it starts the timer and that timer basically waits for the cast bar to go back all the way down and back up which when the timer ends, the bar should be back to max and press the cast button. I found this way to be more accurate and easier to change for better results. Pressing cast as soon as the bar turns blue proved to be inaccurate as by the time my program sent the "space" event to press Cast the cast bar wouldn't be max value anymore and it would be very hit or miss. Therefore, the timer version worked better.

Once the cast event is done, it checks two spots to determine where to go. The center of the screen for a junk item, or the bottom left for the fishing timer. Depending on which one it finds will determine what the program does.

Catching the fish is a different story. The catch bar moves, and the fish moves. This makes it harder to quickly determine if the fish is on a 100% catch block. With that said, the way I check to see if the fish is on a 100% catch block I check the percentage on the right of the bar, more specifically the color of the numbers. As soon as the number is green, I know the fish is on a 100% catch block so I send the "space" event to Catch. I've thought about different ways to implement this, but this was the most accurate way to catch the fish, but not 100% guaranteed because of the faster fish you mentioned. I don't think adding a 1 second delay will fix the issue of the erratic fish, because the fish that fly past the 100% don't give enough time for my program to determine that the fish is in fact on top of a 100% block and if so, send the space event. Also sometimes, the fish don't fly past the 100% block, they are resting on the 75% block and barely touch the 100% block and go right back the 75%. That's another case where my program catches at 75% because the fish was on the 100% for a split second, there's not really a way to guard against that. I tried checking to see if the fish was on a 100% block then double check to see if it was still on a 100% block, but the same issue arises. By the time, the second check determines that yes, indeed it is on a 100% block, send the space event, the fish is already off of it, so it was just redundant.

Hopefully, that answers your question. I'd be more than willing to try some new logic if you think of another way to catch the fish, but that's how it currently works.

**Comment by tiemonl** [comment]
Oops, forgot to answer the bait question. I thought about it, and I could add that logic into the program. However, I find it redundant to add it for a few reasons.

Let's say the user has 100 Legendary bait, 200 Epic bait, 300 Rare bait, and 400 Common bait for simple numbers. The user has 1000 bait in total. 
1. The user can now add up all their bait (1000) and the game will auto switch to the next tier of bait when it is done with the current tier bait and the program will use up all the bait.
2. The user just wants to use their rare bait (300). The user can select the rare bait before fishing and tell the program to fish 300 times and it will use up all of the rare bait.
3. The user wants to use their common and rare bait (700 bait). The use selects common bait, fish 700 times and the program will use up all the common bait and rare bait due to how bait selection works.

**Comment by Forkinator** [comment]
That was a good read. It's nice to learn how these things can work and it definitely answers my questions.  It sounds like you have thought of everything to be honest. I am very much out of ideas at the moment, and I feel it would be difficult to improve upon your program in regards to catching fish. Same goes with the bait. You make a great point about the user being able to just select their desired bait, and their desired amount if they want to use only a certain kind. 


Thank you for taking the time to read all of my ramblings. It was educational for me to hear from and I thank you for your dedication and success with your program.

**Comment by tiemonl** [comment]
No worries at all. I'm always happy to help others. If you have any other questions, let me know! 👍
