### ISSUE TITLE
work on mac

### ISSUE THREAD

**Issue by SetoMoteuchi** [tiemonl/Bit-Heroes-Fishing-Bot#13]
Fish bot does't work on mac.

1. Installed with PlayeOnMac
2. Launched .exe and game on Kongregate
3. set upped platform and right rod
4. clicked find start location
5. got an error screen like the game was closed

**Comment by tiemonl** [comment]
Hey, the reason that this doesn't work on a mac is because i'm using a system32 dependency which won't work on a mac even using mono. I've thought about making a mac version of the fisher, but it would be a lot of time to invest and I'm not sure if it is worth the time for me considering I'm working full time, taking three graduate classes, and currently working on another side project. 

If there is a larger interest for a mac version I could rethink my stance on the matter, but right now it's just not that high on my priority list. I'll leave this issue open to see if it generates more interest. Sorry if this isn't the answer you were looking for :(

**Comment by SetoMoteuchi** [comment]
I''m sorry for answer in late. And thank's to answer me :)

There's no problem, but I want you to notice this issue. It's ok anyway,
thank's

Il giorno gio 4 ott 2018 alle ore 02:19 tiemonl <notifications@github.com>
ha scritto:

**Comment by tiemonl** [comment]
Refer to #29
