### ISSUE TITLE
Window Size Too Small

### ISSUE THREAD

**Issue by PeepsEZ** [tiemonl/Bit-Heroes-Fishing-Bot#14]
**Describe** the bug**
When I open the app, the window size is too small for me to use it. I can maximize the screen size but it's unusable like that.

**To Reproduce**
Steps to reproduce the behavior, i.e:
1. Open the app.

**Expected behavior**
The window should be normal size.

**Screenshots**
Add a screenshot of your Bit Heroes screen and a screenshot of the program GUI.
https://imgur.com/a/gJmBtAb

**Version(please complete the following information):**
 - Kongregate

**Additional context**
I changed my computer resolution and it didn't work. I also I tried using programs that resize windows and it didn't work on this program.

**Comment by tiemonl** [comment]
Hi,
Not sure why that is opening like that, never seen that before. Anyways, I've attached a version of the program that is resize-able. The reason I disabled resizing was because of the debug controls. If they were checked, then the program resizes to show the options on the right. I'm not making a new release for this, as this is a one off issue I'm assuming.

[Click to download](https://github.com/tiemonl/Bit-Heroes-Fishing-Bot/files/2522203/fisher-v1.2.4.1.zip)

Let me know if you have any other issues.

Thanks!
