### ISSUE TITLE
Some security preventions

### ISSUE THREAD

**Issue by VitorFontenelle** [tiemonl/Bit-Heroes-Fishing-Bot#15]
Well, if a lot of people are using this (including me) I don't supose you can get banned, BUT, it's always good to take some precautions.
Here go some suggestions:
1 - Instead of just creating a "click event" in the screen position, simulate a "mouse drag", even if really quick. Things like this tend to be related to bots.
2 - When configuring, select multiple spots in the screen button to click and random between then, clicking the exact same point over and over is easy to track.
3 - Have a nice day :D

**Comment by tiemonl** [comment]
Hey, I agree with you. However, I don't find them necessary currently. The devs know about my program. It's been reported twice, nothing has been done about it. This does not change odds of getting a heavier fish. This doesn't give you 100% catch rate either. It just simulates a person clicking.

Yes, it clicks in the same 5 spots. At first, I had the program press "space" to trigger the clicks, because all the buttons can be pressed with space or by a mouse click. However, that showed to be a problem with different Windows versions and different languages for some reason, so I implemented the click system. 

Also, my program is open source. If I implement clicking random clicking between spots, it would be fairly easy to reverse engineer since the code is visible.

With that said, I can still implement random clicking if you think it is necessary, I don't mind to. I just wanted you to understand why I haven't added it. Let me know what you think!

EDIT: Another point I forgot to mention: A normal user also doesn't randomly click around the screen when fishing normally, so it would easy to find people tapping randomly on the screen during fishing as well.

**Comment by VitorFontenelle** [comment]
I sure think they are not necessary right now, as you said, the game devs doesn't really seem to find this software troubling, and I'm not asking to do it right away, it was just a tip from a future if you're somehow bored in a sunday morning, haha.
Since you already got the idea, you can get this issue as resolved if you want to! Thanks for the attention!

**Comment by tiemonl** [comment]
I like your thought of if I'm bored on a Sunday afternoon. I think a good compromise of what I could do is add the random clicking as a debug options and let users pick if they want to enable/disable random clicking. I will try to add that when I find some time, which might not be until the end of the semester. Thanks for the idea!
