### ISSUE TITLE
start button not found

### ISSUE THREAD

**Issue by Versauen** [tiemonl/Bit-Heroes-Fishing-Bot#19]
**Describe the bug**
After starting up and filling the criteria on both steam and Kongregate
 both displayed could not find start button and I have not idea how to fix this I even tried with the last three versions of the fisher

**Expected behavior**
I expected it to find the start

**Version(Steam and Kongregate tried both):**
Steam
![screenshot 1](https://user-images.githubusercontent.com/46664373/51096472-ec08eb80-1779-11e9-9c44-89fbae49115b.png)

Kongregate
![screenshot 3](https://user-images.githubusercontent.com/46664373/51096540-5e79cb80-177a-11e9-8b20-684e24846939.png)

**Comment by Versauen** [comment]
Running on windows 8 if that helps

**Comment by tiemonl** [comment]
Hey sorry, for the late reply. I figured out the issue (Thank you for the screenshots, very helpful!).

The normal start button should be this color: 
<img width="763" alt="screen shot 2019-01-15 at 6 59 26 am" src="https://user-images.githubusercontent.com/29804333/51179615-151d9f00-1894-11e9-8abe-848d743abf0c.png">

based on your screenshot, your start button is this color: 
<img width="623" alt="screen shot 2019-01-15 at 7 00 20 am" src="https://user-images.githubusercontent.com/29804333/51179641-249ce800-1894-11e9-83d2-a19ded5f7961.png">

I can fix this issue fairly quickly, but I fear that more buttons will be different colors as you get further into the fishing cycle. If you don't mind, would you add me on discord (purplethong#0069) that way I can help you out quicker? I would need your help sending me screenshots of certain screens in the fishing cycle so that I could adjust the colors accordingly for the program to work for you.

**Comment by tiemonl** [comment]
Issue was contrast settings. Changed contrast and issue was fixed.
