### ISSUE TITLE
Application freezes when fishing prompts are delayed

### ISSUE THREAD

**Issue by jchilcher** [tiemonl/Bit-Heroes-Fishing-Bot#2]
**Describe the bug**
While using Bit Heroes in the browser, sometimes the results of a fishing event lag and delay by less than a second, causing the application to prompt casting the line again before the "start" button is available again.  This will cause the bot to remain stuck in the  "Performing Cast" task that freezes the application until force closed or until you manually start a cast in the game

**To Reproduce**
Steps to reproduce the behavior, i.e:
1. start fishing in auto mode
2. eventually the browser will lag and fisher will get stuck

**Expected behavior**
Expected behavior would be to reattempt casting after a delay.

**Screenshots**
Add a screenshot of your Bit Heroes screen and a screenshot of the program GUI.
https://imgur.com/adoKr2C

more definitive proof of a crash:
https://imgur.com/tWR6uK0

**Version(please complete the following information):**
 - Kongregate

**Additional context**

**Comment by tiemonl** [comment]
As far as this program adding lag to chrome, I don't think this program is the cause of it. There's nothing that could add lag as this program is just clicking the mouse at specific times in specific places. Perhaps it could be an extension in chrome? Also, "Chrome is being controlled by automated test software." that isn't part of the program, so there might be something else in the background causing lag. I could be wrong, I'm just trying to think of things that could cause lag.

As far the program crashing, I overlooked lag or potentially missing a step. I will work on a fix to set a timeout if a specific task isn't done by a certain amount of time. I will try to make it so the program can catch up to where it was rather than fully stop, but that is TBD. I will try to have a fix out by Saturday. Sorry for the inconvenience.

**Comment by jchilcher** [comment]
No worries, and thank you for the response.  I took a look at the code and see that some of the cues are base off of time waiting. Thus if a little lag is introduced, the BackgroundWorker can become out of sync and hang while trying to perform another cast.  

I see you're already checking for specific colors in certain areas like the start button; perhaps having color cues for more steps may resolve any syncing issues?  I'll get back to you once I find something more useful to report. 

EDIT: I was using chromedriver to spin up an instance of chrome, I tried your application on a normal chrome browser and got the same result. it isnt because of your application, it is because chrome crashes when running bit heroes for long enough.

**Comment by tiemonl** [comment]
If I give a timeout for commands, I can then go check each pixel location and their color to determine where the user is and pick back up where it should be. I will try to make a fix for that. So if it does become out of sync, for example after 10-20 seconds of no casting result, it will check each pixel location to determine where the program should be and pick back up from there. My fear is that it possibly messes up the amount of bait used, but that shouldn't be a big deal.

**Comment by tiemonl** [comment]
Is this issue still happening?

**Comment by CrazedF001** [comment]
Describe the bug
I am on steam.
bot works fine until your catch comes up on the "Trade" screen then just freezes the app due to inputs being locked out.
It seems to want to click start instead of trade button.
There is one more window displaying rewards after this trade screen as well.
Esc button is also not responding. Is there a universal kill bot button?
I need to ctrl+alt+del and bring up task manager and restart everything, to do the same thing again.
I have it on 800x600 windowed running through steam

Version(please complete the following information):

Steam

**Comment by tiemonl** [comment]
@CrazedF001 What OS are you running? I seem to be getting a few people running windows 7 that are running into this issue.

**Comment by tiemonl** [comment]
@jchilcher have you ran any of the newer versions to see if you are still getting issue?

**Comment by CrazedF001** [comment]
Sorry for the delay!
I re-downloaded the latest to make sure.
I still have the problem as described.
I am running windows 7 x64
Is there anything I could do to help? I dont receive a dump crash as I need to force close apps to reclaim the whole system.

**Comment by tiemonl** [comment]
@CrazedF001 I don't have a windows 7 machine to test my bot on. If you were willing to help me debug each spot it breaks and relay information for me, That would be extremely helpful, but also tedious on your part and I wouldn't expect you to do that. 

My current cancel auto mode waits for the fishing bot to finish the current fish its on, but I guess I probably should just cancel it outright when people press cancel. That's a quick fix and will have in the next release 1.2.5

**Comment by CrazedF001** [comment]
I would not have a problem with this, but Ill leave it up to you.
Im not into coding but I have built a few memory editors for personal use.
idk if you would want to communicate through here or?
I have unfettered access to my pc, as I am the only user.
Thanks for being an active dev tiemonl!

**Comment by tiemonl** [comment]
@CrazedF001 I would make a build that you run and give me information on where the cursor goes and keep doing that until it works with no issue. If you have discord, we could communicate through there? Just send me your tag and I’ll add you.

**Comment by CrazedF001** [comment]
discord --------
i can take photos if needed as well, i have it hooked to a 55" tv (16:9)
