### ISSUE TITLE
Bot can't find the fish button.

### ISSUE THREAD

**Issue by ghost** [tiemonl/Bit-Heroes-Fishing-Bot#21]
**Describe the bug**
It won't fish.

**To Reproduce**
Steps to reproduce the behavior, i.e:

**Expected behavior**
It to start fishing.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/48146200/53852609-7f3ef000-3f77-11e9-8c9a-fc8cd7607c1f.png)

**Version(please complete the following information):**
 -Kongregate

**Additional context**
Other things like this don't work either.

**Comment by tiemonl** [comment]
Hey, it seems like your browser window is not zoomed in, so that's good. However, it seems as if your windows zoom settings are up. Would you mind checking those for me? (right click desktop, display settings) you're looking for this screen:
![image](https://user-images.githubusercontent.com/29804333/53888378-5dcf1a00-3ff2-11e9-8b56-ac71eeec1354.png)

Can you check to see that your resolution is at the default setting and that the scale and layout is set to 100%

**Comment by ghost** [comment]
It worked!!!!
Thank you!

**Comment by tiemonl** [comment]
Glad it’s working now!
