### ISSUE TITLE
Can't find start button on linux

### ISSUE THREAD

**Issue by guipaiva** [tiemonl/Bit-Heroes-Fishing-Bot#36]
**Describe the bug**
It doesn't found the start button

**To Reproduce**
1. Execute the jar file on terminal
2. See error 

**Expected behavior**
Should find the start button

**Screenshots**
![image](https://user-images.githubusercontent.com/48967900/64394321-099e0480-d02c-11e9-9528-e3ec52041121.png)

**Version:**
 - Kongregate on browser

**Additional context**
OS: Ubuntu 19.04
I've tested both in Kongregate on Firefox and Chromium.

**Comment by tiemonl** [comment]
Could you add me on discord? `purplethong#0069` Windows uses sRGB and Mac uses RGB, I assumed Linux would use the same color scheme as mac, but it turns out I was wrong. If you don't mind, I would need a little help figuring out which color scheme Linux uses so that I can adjust the program accordingly.
