### ISSUE TITLE
Bot crashing due to low speed or FPS

### ISSUE THREAD

**Issue by TheCobalox** [tiemonl/Bit-Heroes-Fishing-Bot#47]
GG

**Comment by tiemonl** [comment]
> The bot crashes when it presses the X to close the shell reward due to making it too fast on certain pcs
To Reproduce
Steps to reproduce the behavior, i.e:
I made the test on both kong and steam, and it seems to bother on both, i think the obvious reason is to have a low fps pc, the bot tries to click too fast on the X on the shell button, even before it appears due to lag/low fps, making it go to the cast line before closing the shell menu and then crashing.
Additional context
i think it's not that hard to fix, and would help a lot, it just needs to have a lower speed to make the choices, or at least a drag, e.g.: slow-normal in the bot .exe
hope you can help us with this, thanks

Hey, sorry for the late reply... Were you able to get this resolved. It wouldn't be a hard fix to implement a slow mode toggle if you weren't able to fix it. Let me know.
