### ISSUE TITLE
The application freezes (Not Responding) 

### ISSUE THREAD

**Issue by FrogenYozurtZA** [tiemonl/Bit-Heroes-Fishing-Bot#6]
The application always goes into not responding when i click Autofish, regardless of how long i wait it does not unfreeze.

I setup the start button location as per the instructions and am running the game on 800x600 using the steam client.

Running Win10 64 bit. Fully patched etc. I have also tried all versions of the fisher and the problem is consistent with each version.

any help would be very much appreciated.

**Comment by tiemonl** [comment]
Hey. Are you on more than one monitor? 100% zoom and default resolution? If you post your discord tag I can message you quicker as well.

**Comment by FrogenYozurtZA** [comment]
Thanks for the fast reply man.

My discord tag is ------.

I am using a dual monitor setup but both the application and the BH client are on the main monitor.

What do you mean about my zoom and resolution? Like the monitor settings?

**Comment by tiemonl** [comment]
What is the #0000 tag for discord?

**Comment by tiemonl** [comment]
I sent you a friend request on discord

**Comment by tiemonl** [comment]
I've seen this issue 4 other times. This issue occurs when the user has multiple monitors that are different resolutions. A work around for this currently is to align the highest resolution monitor to the left and descend monitor resolutions on the **top right** as in the screenshot below: 
![Monitor setup](https://i.imgur.com/AE5vCde.png)

After fishing you can set your monitors back up. This occurs because of how my code takes a picture of the screen. I will work on a fix as soon as I can. I am leaving this issue open until I fix my screenshot function.
