### ISSUE TITLE
Fisher stuck at "waiting for cast result"

### ISSUE THREAD

**Issue by Echonium** [tiemonl/Bit-Heroes-Fishing-Bot#7]
**Describe the bug**
The fisher does click on "start" successfully, then casts, but never actually fishes, indicates that it's "waiting for cast result". Happens every time.

**Version(please complete the following information):**
 - Steam

Let me know if you need any more information.

**Comment by tiemonl** [comment]
Which version of the bot are you using?
Are you on 800x600 resolution for bit heroes?
Are you on windows 10?
If so, are you using the default resolution?

**Comment by ValaraukarNoir** [comment]
Hi,
I tryed your soft on Kongregate (firefox) AND Steam. and i follow all your requirements on steam (screen resolution).
On 6 fishing test, i always got the 100% on steam and for the only one test on kongregate 75%.
In both cases i caught a fish, BUT the program was stuck right after the first fishing result.
On Steam,  you "simply" need to send "escape" key 2 time to return to fishing screen (if a fish is caught) and 1 "escape" if no fish is caught.

Currently, it freeze computer mouse / screen / and your program (i still can use Ctrl + Alt + Sup to close your soft).
System : 
Windows 7 x64 / firefox (latest) / steam

I hope you will solve that fast because the fishing is just painfull , not funny and time consuming. ( i stop "play" once i got a rare fish because of that)

Have a nice day

EDIT : where are stored the screenshoot ? or temporary files ?

**Comment by tiemonl** [comment]
@ValaraukarNoir can you send me your discord tag so i can message you?

**Comment by ValaraukarNoir** [comment]
i do not have discord ^^

**Comment by tiemonl** [comment]
@ValaraukarNoir would you be able to make one? it would make it a lot easier

**Comment by ValaraukarNoir** [comment]
--------

**Comment by Echonium** [comment]
@tiemonl 
I tried both the 1.2.2 and the 1.2.0
I did set the resolution at 800*600
I am using W7 x64, at the native resolution of my screen, without software zooming

**Comment by tiemonl** [comment]
@Echonium can you send me your discord tag as well?

**Comment by Echonium** [comment]
@tiemonl I believe you can reach me at ----

**Comment by tiemonl** [comment]
fixed here: e2e5514
